### ISSUE TITLE
Different error message with encoding/json

### ISSUE THREAD

**Issue by rleungx** [segmentio/encoding#11]
Here is an example
json.go
```
package main

import (
	"encoding/json"
	"fmt"
	"math"
)

type A struct {
	B float64
}

func main() {
	c := A{
		B: math.NaN(),
	}
	_, err := json.Marshal(c)
	fmt.Println(err)
}
```

```
diff json.go json_segmentio.go
< 	"encoding/json"
---
> 	"github.com/segmentio/encoding/json"
```
The output of `json.go`:
```
json: unsupported value: NaN
```
The output of `json_segmentio.go`:
```
json: unsupported value: unsupported value
```

**Comment by pelletier** [comment]
Hi, thank you for trying out segmentio/encoding!

Although this package aims to be a drop-in replacement of encoding/json, it does not guarantee the same error messages. It will error in the same cases as the standard library, but the exact error message may be different.

That being said, we should look into adding an indication of what value is supported in the error message, @achille-roussel @yolken-segment

**Comment by achille-roussel** [comment]
Yes, like @pelletier said we generally don't aim to match the error messages exactly, because these have been changing quite a bit between Go versions, and the `encoding/json` package doesn't guarantee that they'll retain the same error messages.

In that case tho, it does seem like our error messaging is not ideal, I'll look into it 👍 

Thanks for reporting @rleungx !
